# render.yaml - final verified version
previewsEnabled: true

databases:
  - name: codingal-db
    databaseName: codingal
    databaseType: postgres
    postgresMajorVersion: 17

services:
  - type: web
    name: codingal-backend
    runtime: docker
    rootDir: backend/app
    dockerfilePath: Dockerfile
    plan: starter
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        value: ""
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "0.0.0.0"
      - key: PORT
        value: "8000"
    # releaseCommand: python manage.py migrate

  - type: web
    name: codingal-frontend
    runtime: static
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    buildOutputPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: ""

  - type: web
    name: codingal-pgadmin
    runtime: docker
    dockerImage: dpage/pgadmin4:7
    plan: starter
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        sync: false
      - key: PGADMIN_DEFAULT_PASSWORD
        sync: false
