<?php
// warning.php - legacy-style PHP generated page
$title = "CodingAl Backend - WARNING";
$message = "You are visiting the backend API area. Unauthorized access is prohibited.";
$year = date("Y");
$ascii = "
  ____ ___  _   _  ____    _    _   _ ___ _   _
 / ___/ _ \\| \\ | |/ ___|  / \\  | \\ | |_ _| \\ | |
| |  | | | |  \\| | |  _  / _ \\ |  \\| || ||  \\| |
| |__| |_| | |\\  | |_| |/ ___ \\| |\\  || || |\\  |
 \\____\\___/|_| \\_|\\____/_/   \\_\\_| \\_|___|_| \\_|
";

$html = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{$title}</title>
<style>
  /* legacy / left-aligned / monospace feel */
  html,body{height:100%;margin:0;background:#f2f2f2;color:#111;font-family:Consolas,Monaco,'Andale Mono','Courier New',monospace;}
  .wrap{max-width:900px;margin:40px auto; padding:20px; background:#fff;border-left:6px solid #cc0000; box-shadow:0 0 0 rgba(0,0,0,0);}
  pre.ascii{margin:0 0 18px 0; color:#cc0000; font-weight:700; line-height:1;}
  h1{font-size:18px;margin:0 0 8px 0;color:#990000;}
  p{margin:6px 0;color:#222; font-size:14px;}
  .notice{background:#fff4e5;border:1px solid #ffd59e;padding:10px;margin-top:12px;color:#663300;}
  .meta{margin-top:18px;font-size:12px;color:#666;}
  a.btn{display:inline-block;margin-top:12px;padding:8px 14px;background:#333;color:#fff;text-decoration:none;border-radius:3px;font-size:13px;}
  /* keep layout strictly left-aligned */
  .wrap, pre.ascii { text-align:left; }
</style>
</head>
<body>
  <div class="wrap">
    <pre class="ascii">{$ascii}</pre>
    <h1>{$title}</h1>
    <p>{$message}</p>
    <div class="notice"><strong>WARNING:</strong> This endpoint is for service/administration only. Activity is logged.</div>
    <a class="btn" href="/">Return to site</a>
    <div class="meta">Generated by server · {$year}</div>
  </div>
</body>
</html>
HTML;

echo $html;
